### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by LeoJHarris**
Updates XF to latest and Xamarin.Android.Support Libs to 27.0.2.1

### CODE REVIEW

**Comment by LeoJHarris** [comment]
Builds successfully and deploys to iOS and Android.

**Comment by stormlion227** [comment]
Ok. I'll check and update in few hours.

**Comment by aherrick** [comment]
@stormlion227 great! ooking for new Nuget. Thanks!

**Comment by aherrick** [comment]
Did the NUGET get released?

**Comment by stormlion227** [comment]
I've updated nuget just now. I'm very sorry for lateness.

**Pull request merged**
